DROP SEQUENCE SEQ_USERCOMMENT;

CREATE SEQUENCE SEQ_USERCOMMENT;

DROP TABLE USERCOMMENT;

CREATE TABLE USERCOMMENT (
	REPNO NUMBER PRIMARY KEY
	, NAME VARCHAR2(20) NOT NULL
	, TEXT VARCHAR2(500) NOT NULL
	, CREATE_DATE DATE DEFAULT SYSDATE
);